import csv
with open('filegame_1.csv', 'w') as filecsv:
    rs = csv.writer(filecsv,delimiter=',')
    rs.writerow(['Name','Platform','Year','Genre','Global_Sales'])
    rs.writerow(['The sim 4','PC','2013','Simulation','2.97'])
    rs.writerow(['Battlefield 4','PC','2013','','1.4'])
    rs.writerow(['Football Manager 2014','PC','','Sports','0.71'])
    rs.writerow(['Call of Duty: Black Ops 3','PC','2014','','0.23'])
    rs.writerow(['Assassin Creed Syndicate','PC','2014','Action','0.2'])
    rs.writerow(['The Sims 4: Get Together','PC', '2014','Simulation','0.19'])
    rs.writerow(['FIFA 16','PC','2014','Sport','0.18'])
    rs.writerow(['Dark Soul II','PC','2014','Role_Playing','0.18'])
    rs.writerow(['Battlefield: Hardline','PC','2014','','0.14'])
    rs.writerow(['Batman: Arkham Knight','PC','2014','Action','0.13'])
    rs.writerow(['Assassin Creed:Rogue','','2015','Action','0.07'])
    rs.writerow(['FIFA 17','','2015','Sports','0.05'])
    rs.writerow(['Dark Soul III','PC','2015','Role_Playing','0.05'])
    rs.writerow(['The sim 4:Spa Day','PC','2016','Simulation','0.04'])
    rs.writerow(['Divinity:Original Sin','PC','2016','Role_Playing',''])
    rs.writerow(['The Sims 4:Luxury','PC','2016','Simulation',''])
    rs.writerow(['Assassin Creed:Rogue','PC','2016','Action','0.01'])
    filecsv.close()
print('Done writing')